### ISSUE TITLE
It looks broken

### ISSUE THREAD

**Issue by dev4dev** [CocoaPods/Strata#7]
I want to checkout cocoapods.org, so I run ` rake bootstrap:cocoapods` and this ends up with 

```
...
Cloning cocoapods.org
git clone https://github.com/CocoaPods/cocoapods.org.git cocoapods.org
Cloning into 'cocoapods.org'...
remote: Counting objects: 3401, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 3401 (delta 1), reused 0 (delta 0), pack-reused 3386
Receiving objects: 100% (3401/3401), 3.29 MiB | 764.00 KiB/s, done.
Resolving deltas: 100% (2215/2215), done.
Checking connectivity... done.
Updating submodules...
Cloning into 'shared'...
remote: Counting objects: 1264, done.
remote: Total 1264 (delta 0), reused 0 (delta 0), pack-reused 1264
Receiving objects: 100% (1264/1264), 7.38 MiB | 850.00 KiB/s, done.
Resolving deltas: 100% (772/772), done.
Checking connectivity... done.
Installing gems
cd middleman && bundle install
sh: line 0: cd: middleman: No such file or directory
rake aborted!
Command failed with status (1): [cd middleman && bundle install...]
/Users/devil/Repos/Strata/cocoapods.org/Rakefile:16:in `block (2 levels) in <top (required)>'
/Users/devil/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler.rb:236:in `block in with_clean_env'
/Users/devil/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler.rb:223:in `with_original_env'
/Users/devil/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler.rb:229:in `with_clean_env'
/Users/devil/Repos/Strata/cocoapods.org/Rakefile:15:in `block in <top (required)>'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bootstrap
(See full trace by running task with --trace)

--------------------------------------------------------------------------------
Bootstrapping the cocoapods.org repository
--------------------------------------------------------------------------------

Bootstrapping cocoapods.org
rake aborted!
LoadError: cannot load such file -- twitter
/Users/devil/Repos/Strata/cocoapods.org/Rakefile:3:in `require'
/Users/devil/Repos/Strata/cocoapods.org/Rakefile:3:in `<top (required)>'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

Disk usage: 16M

```

OSX: 10.9.5
rvm ruby: 2.1.3

**Comment by floere** [comment]
Can you run `bundle exec rake bootstrap:cocoapods`, please, and see if that resolves things?

**Comment by dev4dev** [comment]
Nope, the same result

**Comment by floere** [comment]
I can't reproduce it with current Strata master `b71dc14b7472947603b6bb46a34045d498c45835`.

**Comment by dev4dev** [comment]
I tried on laptop (10.10.2), the same situation. It seams like it doesn't see already installed gems. I tried some strange stuff, but it didn't help. So I give up.

**Comment by orta** [comment]
I wonder if there's some additional bundle context happening that we're not aware of.

**Comment by segiddins** [comment]
Sounds like we're not using `bundle exec` somewhere.

**Comment by squarefrog** [comment]
I'm having this same issue today. Also using `rvm`.

    $ gem list

    *** LOCAL GEMS ***
    ....
    twitter (5.14.0)
    ....

Interestingly, 

    $ which twitter
    twitter not found

**Comment by floere** [comment]
@squarefrog Try `gem which twitter`. I don't think the twitter lib has a binary.
@segiddins Sounds like it.

**Comment by orta** [comment]
I also get 

```
$ which twitter
twitter not found
```

**Comment by floere** [comment]
@orta Why do you think there needs to be a twitter binary? (See my comment)

**Comment by squarefrog** [comment]
> Try gem which twitter. I don't think the twitter lib has a binary.
TIL.

```bash
$ which gem twitter
gem () {
        \typeset result
        (
                \typeset rvmrc
                rvm_rvmrc_files=("/etc/rvmrc" "$HOME/.rvmrc")
                if [[ -n "${rvm_prefix:-}" ]] && ! [[ "$HOME/.rvmrc" -ef "${rvm_prefix}/.rvmrc" ]]
                then
                        rvm_rvmrc_files+=("${rvm_prefix}/.rvmrc")
                fi
                for rvmrc in "${rvm_rvmrc_files[@]}"
                do
                        [[ -s "${rvmrc}" ]] && source "${rvmrc}" || true
                done
                unset rvm_rvmrc_files
                command gem "$@"
        ) || result=$?
        hash -r
        return ${result:-0}
}
twitter not found
```

After doing some reading, I see thats nothing really to worry about as `gem which XX` just searches for `lib/` folders?

======

Anyway. Moving forward - the following works:

```bash
$ cd cocoapods.org
$ bundle exec rake bootstrap
```

As I understand it, `$ bundle exec` provides access to the gems in the current bundle. Is the fact that `cocoapods.org` is nested causing issue?

**Comment by floere** [comment]
It's `gem which twitter`.

**Comment by squarefrog** [comment]
Oh yes.. 

```bash
$ gem which twitter
/Users/pi/.rvm/gems/ruby-2.1.3/gems/twitter-5.14.0/lib/twitter.rb
```

**Comment by floere** [comment]
@dev4dev Can you try again?

**Comment by lazerwalker** [comment]
I was having this issue. What solved it for me was manually going into the `cocoapods.org` directory and running `bundle install` and `rake bootstrap` from within there, rather than the parent project directory.

**Comment by lazerwalker** [comment]
Which I believe is basically the same solution as just `bundle exec rake bootstrap` from inside there, as I'm fairly certain the latter automatically triggers the needed `bundle install` when/if it doesn't find the proper gems.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/cocoapods.org/commit/04f74925e442732fc8d68cff2171a285678ca28f should let you run `rake bootstrap` now

**Comment by dev4dev** [comment]
@floere yes, this step works now :+1: 
But here is another problem

```
/Users/devil/Repos/Strata
[git:master]
❯❯❯ bundle exec rake db:migrate

--------------------------------------------------------------------------------
Performing migration
--------------------------------------------------------------------------------
rake db:migrate RACK_ENV=test
rake aborted!
LoadError: cannot load such file -- sequel
/Users/devil/Repos/Strata/Humus/config/init.rb:11:in `require'
/Users/devil/Repos/Strata/Humus/config/init.rb:11:in `<top (required)>'
/Users/devil/Repos/Strata/Humus/Rakefile:12:in `require'
/Users/devil/Repos/Strata/Humus/Rakefile:12:in `block in <top (required)>'
/Users/devil/Repos/Strata/Humus/Rakefile:58:in `block (2 levels) in <top (required)>'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => env
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake db:migrate RACK_ENV=test...]
/Users/devil/Repos/Strata/Rakefile:488:in `block in run_humus_rake_task'
/Users/devil/Repos/Strata/Rakefile:487:in `chdir'
/Users/devil/Repos/Strata/Rakefile:487:in `run_humus_rake_task'
/Users/devil/Repos/Strata/Rakefile:266:in `block (2 levels) in <top (required)>'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/devil/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by lazerwalker** [comment]
I was having some trouble with this a few days ago as well. If you go into the Humus directory and run `bundle exec rake db:bootstrap`, does it work?

**Comment by segiddins** [comment]
@lazerwalker works fine for me

**Comment by lazerwalker** [comment]
@segiddins To rephrase what I said: running `rake db:migrate` from the root strata directory did not work for me, but running `rake db:bootstrap` from within Humus did (give or take a `bundle exec` for either one), so @dev4dev should try that.

**Comment by squarefrog** [comment]
The above worked for me. So to summarise

```
git clone https://github.com/cocoapods/Strata.git
cd Strata
bundle install
rake bootstrap:cocoapods
cd Humus
bundle exec rake db:bootstrap
cd ../cocoapods.org
bundle exec foreman start --port 4000
```

Note: I had to start foreman on port 4000, as the default mentioned in the cocoapods.org readme (3000) didn't work for me. Foreman started just fine, but going to `http://localhost:3000` produced nothing.

**Comment by floere** [comment]
Just a heads up: cocoapods.org and Strata both were changed quite a bit, and it seems that we did not update the READMEs and/or polish as well as we should. Thanks for your patience!

@squarefrog The default port for foreman is 5000. And if going to 3000 produced nothing (I assume an empty page), then you may have something running there.

**Comment by squarefrog** [comment]
That'll be why. I'll PR the cocoapods README.

**Comment by squarefrog** [comment]
I've just followed the README steps from scratch and everything seems to work well now. I get a couple of aborted rakes for cocoadocs. I'll create an issue over there.

```
Bootstrapping cocoadocs.org
rake aborted!
LoadError: cannot load such file -- rubocop/rake_task
/Users/pi/git/Strata/cocoadocs.org/Rakefile:1:in `require'
/Users/pi/git/Strata/cocoadocs.org/Rakefile:1:in `<top (required)>'
/Users/pi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/pi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by dev4dev** [comment]
Thanks, everything is fine with db:migrate now, if run it from Humus directory.

Now it's time to find out why it returns 404 when you trying to expand pod details :smile_cat: 

```"NetworkError: 404 Not Found - http://devil:5000/pods/AFNetworking/inline"```
